name: fullstack_K17_db
services:
  postgres_db:
    image: postgres:17
    environment:
      POSTGRES_USER: f8
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6380:6379

  backend:
    build:
      context: ./Backend
    container_name: booking-backend
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - ./Backend/.env # Sửa chữ B viết hoa
    environment:
      # Ghi đè cấu hình kết nối trong container trỏ về mạng nội bộ của docker
      - DATABASE_URL=postgresql://f8:123456@postgres_db:5432/booking_movie?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379 # Port nội bộ của redis trong docker
    depends_on:
      - postgres_db # Sửa từ postgres thành postgres_db
      - redis

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_URL=http://3.25.189.3:3001/api
        - NEXT_PUBLIC_WEB_URL=http://3.25.189.3:3000
    container_name: booking-frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_db:

